export default [
  {
    username: 'Jamerrone',
    repoUrl: 'https://github.com/Jamerrone/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Jamerrone',
    repoUrl: 'https://github.com/Jamerrone/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'one-primary-action-per-screen',
    principleName: 'One primary action per screen',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Jamerrone',
    repoUrl: 'https://github.com/Jamerrone/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'strong-visual-hierarchies-work-best',
    principleName: 'Strong visual hierarchies work best',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Jajan20',
    repoUrl: 'https://github.com/jajan20/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Jajan20',
    repoUrl: 'https://github.com/jajan20/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'one-primary-action-per-screen',
    principleName: 'One primary action per screen',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Jajan20',
    repoUrl: 'https://github.com/jajan20/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'strong-visual-hierarchies-work-best',
    principleName: 'Strong visual hierarchies work best',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'RobinFrugte97',
    repoUrl: 'https://github.com/RobinFrugte97/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'one-primary-action-per-screen',
    principleName: 'One primary action per screen',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'RobinFrugte97',
    repoUrl: 'https://github.com/RobinFrugte97/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'appearance-follows-behavior',
    principleName: 'Appearance follows behavior',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'RobinFrugte97',
    repoUrl: 'https://github.com/RobinFrugte97/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'strong-visual-hierarchies-work-best',
    principleName: 'Strong visual hierarchies work best',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Meesrutten',
    repoUrl: 'https://github.com/meesrutten/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'interfaces-exist-to-enable-interaction',
    principleName: 'Interfaces exist to enable interaction',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Meesrutten',
    repoUrl: 'https://github.com/meesrutten/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'one-primary-action-per-screen',
    principleName: 'One primary action per screen',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Meesrutten',
    repoUrl: 'https://github.com/meesrutten/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'progressive-disclosure',
    principleName: 'Progressive disclosure',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Chanakarn',
    repoUrl: 'https://github.com/niyorn/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Chanakarn',
    repoUrl: 'https://github.com/niyorn/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'strong-visual-hierarchies-work-best',
    principleName: 'Strong visual hierarchies work best',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Chanakarn',
    repoUrl: 'https://github.com/niyorn/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'smart-organization-reduces-cognitive-load',
    principleName: 'Smart organization reduces cognitive load',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Sam Guliker',
    repoUrl: 'https://github.com/sam-guliker/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Sam Guliker',
    repoUrl: 'https://github.com/sam-guliker/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'one-primary-action-per-screen',
    principleName: 'One primary action per screen',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Sam Guliker',
    repoUrl: 'https://github.com/sam-guliker/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'consistency-matters',
    principleName: 'Consistency matters',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Vriesm060',
    repoUrl: 'https://github.com/vriesm060/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Vriesm060',
    repoUrl: 'https://github.com/vriesm060/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'strong-visual-hierarchies-work-best',
    principleName: 'Strong visual hierarchies work best',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Vriesm060',
    repoUrl: 'https://github.com/vriesm060/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'smart-organization-reduces-cognitive-load',
    principleName: 'Smart organization reduces cognitive load',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'NielsFS',
    repoUrl: 'https://github.com/NielsFS/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'NielsFS',
    repoUrl: 'https://github.com/NielsFS/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'consistency-matters',
    principleName: 'Consistency matters',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'NielsFS',
    repoUrl: 'https://github.com/NielsFS/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'smart-organization-reduces-cognitive-load',
    principleName: 'Smart organization reduces cognitive load',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Dipsaus9',
    repoUrl: 'https://github.com/dipsaus9/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Dipsaus9',
    repoUrl: 'https://github.com/dipsaus9/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'consistency-matters',
    principleName: 'Consistency matters',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Dipsaus9',
    repoUrl: 'https://github.com/dipsaus9/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'provide-a-natural-next-step',
    principleName: 'Provide a natural next step',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Yoeripasmans',
    repoUrl: 'https://github.com/yoeripasmans/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'clarity-is-job-1',
    principleName: 'Clarity is job #1',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Yoeripasmans',
    repoUrl: 'https://github.com/yoeripasmans/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'strong-visual-hierarchies-work-best',
    principleName: 'Strong visual hierarchies work best',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Yoeripasmans',
    repoUrl: 'https://github.com/yoeripasmans/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'progressive-disclosure',
    principleName: 'Progressive disclosure',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Leoniesmits',
    repoUrl: 'https://github.com/leoniesmits/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'keep-users-in-control',
    principleName: 'Keep users in control',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Leoniesmits',
    repoUrl: 'https://github.com/leoniesmits/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'strong-visual-hierarchies-work-best',
    principleName: 'Strong visual hierarchies work best',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Leoniesmits',
    repoUrl: 'https://github.com/leoniesmits/web-design/',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'progressive-disclosure',
    principleName: 'Progressive disclosure',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Japgroevemaker',
    repoUrl: 'https://github.com/japgroevemaker/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'one-primary-action-per-screen',
    principleName: 'One primary action per screen',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Japgroevemaker',
    repoUrl: 'https://github.com/japgroevemaker/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'provide-a-natural-next-step',
    principleName: 'Provide a natural next step',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
  {
    username: 'Japgroevemaker',
    repoUrl: 'https://github.com/japgroevemaker/web-design',
    thumbnail:
      'https://cdn.dribbble.com/users/25514/screenshots/4362077/camping_illustration-ramotion.png',
    principleID: 'appearance-follows-behavior',
    principleName: 'Appearance follows behavior',
    principleDescription: '',
    likes: Math.floor(Math.random() * 100) + 1,
    dislikes: Math.floor(Math.random() * 100) + 1,
  },
];
